---
- hosts: gerenciado
  become: yes
  tasks:
    - name: Instalar o servidor DHCP
      yum:
        name: dhcp
        state: latest

    - name: "Read users from CSV file and return a dictionary"
      read_csv:
        path: /desafio_rhel/machines.csv
        fieldnames: HOSTNAME,IP,MAC
        delimiter: ','
      register: machines
      delegate_to: localhost

    - name: "Copia o arquivo dhcpd.conf com os IPs host corretos"
      template:
        src: /desafio_rhel/dhcpd.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: 0640
      notify: "Reiniciar o dhcp"

  handlers:
    - name: "Reinicialização do DHCP Server"
      service:
        name: dhcpd
        state: restarted
      listen: "Reiniciar o dhcp"
