---
- hosts: gerenciado
  tasks:
    - name: Instalar o apache
      yum:
        name: httpd
        state: latest
    - name: Iniciar e habilitar o módulo httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Copia index.html para /var/www/html
      copy:
        src: /desafio_rhel/index.html
        dest: /var/www/html
        owner: apache
        group: apache
        mode: 0644
        remote_src: no
      notify: "Reiniciar o Apache"
  handlers:
    - name: "Reinicialização do apache"
      service:
        name: httpd
        state: restarted
      listen: "Reiniciar o Apache"
